baseURL = "https://ubuntuupdate.com"
title = "Ubuntu Update"
languageCode = "en-gb"
theme = "paper"
enableGitInfo = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Alan Pope"

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 6

[[menu.main]]
    url = "/contact"
    name = "Contact"
    weight = 7

[[menu.main]]
    url = "/index.xml"
    name = "RSS"
    weight = 8

